### PR TITLE
Update for private Repos & Markdown for release notes

### PR DESCRIPTION
**Pull request by walker**
This update provides access to private repos, though current users will need to re-authorize their repository.

Also, I fixed some of the formatting on the release entries (including an outright bug that referenced commit, not release).

And now the markdown-formatted release notes are rendered into HTML.

### CODE REVIEW

**Comment by vilmosioo** [comment]
After testing this PR, I suspect there is a bug introduced by changing the scope to allow private repos and organisation access. The API might be different. It fails after connecting to Github. 

I'll investigate further, maybe it's nothing.

**Comment by walker** [comment]
Weird. I'm using this in a production setting right now...works like a charm.

**Comment by vilmosioo** [comment]
Good to hear :)

Just curious. Do you have any organisations?

**Comment by walker** [comment]
Yes.

**Pull request merged**
